from playwright.sync_api import Page, expect



#Realizado por Lorena
def test_compra_con_tarjeta_vacia(page: Page):
    print("Given el usuario abre la página de productos Nuestros Productos | Vida Verde ")
    page.goto("https://web-qa.dev.adalab.es/products")
    print("When filtra por nombre “palas”")
    page.get_by_role("searchbox", name="Nombre").fill("palas")
    print("And agrega el producto al carrito")
    page.get_by_role("button", name="Añadir Juego de Palas al").click()
    print("And visita la página del carrito")
    page.get_by_role("link", name="Carrito de compra").click()
    print("And hace click en proceder al pago")
    page.get_by_role("link", name="Proceder al Pago").click()
    print("Then debe ver el resumen del pedido con")
    expect(page.get_by_role("heading", name="Resumen del Pedido")).to_be_visible()
    print("then debe ver el producto “juego de palas”")
    expect(page.get_by_text("Juego de Palas")).to_be_visible()
    print("then debe ver precio del producto “15.99”")
    expect(page.get_by_role("listitem").filter(has_text="Juego de Palas15.99 €").locator("data")).to_be_visible()
    print("then debe ver el subtotal “15.99”")
    expect(page.get_by_role("definition").filter(has_text="15.99 €").locator("data")).to_be_visible()
    print("then debe ver el IVA “3.36”")
    expect(page.get_by_text("3.36 €")).to_be_visible()
    print("then debe ver el envio “5”")
    expect(page.get_by_text("5.00 €")).to_be_visible()
    print("and debe ver el total “24”")
    expect(page.get_by_text("24.35 €")).to_be_visible()
    print("When rellena el campo de nombre válido “María Díaz”")
    page.get_by_role("textbox", name="Nombre Completo *").fill("Maria Diaz")
    print("And rellena el campo email válido “test@gmail.com”")
    page.get_by_role("textbox", name="Email *").fill("test@gmail.com")
    print("And rellena la dirección valida “Calle Aragon, 25, Madrid”")
    page.get_by_role("textbox", name="Dirección *").fill("Calle Aragon, 25, Madrid")
    print("And hace click en completar compra")
    page.get_by_role("button", name="Completar Compra").click()
    print("Then el usuario permanece en la página de check out Finalizar Compra | Vida Verde ")
    expect(page.get_by_role("heading", name="Finalizar Compra")).to_be_visible()


    #Realizado por Lorena
def test_compra_con_tarjeta_invalida(page: Page):
    print("Given el usuario abre la página de productos Nuestros Productos | Vida Verde ")
    page.goto("https://web-qa.dev.adalab.es/products")
    print("When filtra por nombre “palas”")
    page.get_by_role("searchbox", name="Nombre").fill("palas")
    print("And agrega el producto al carrito")
    page.get_by_role("button", name="Añadir Juego de Palas al").click()
    print("And visita la página del carrito")
    page.get_by_role("link", name="Carrito de compra").click()
    print("And hace click en proceder al pago")
    page.get_by_role("link", name="Proceder al Pago").click()
    print("Then debe ver el resumen del pedido con")
    expect(page.get_by_role("heading", name="Resumen del Pedido")).to_be_visible()
    print("then debe ver el producto “juego de palas”")
    expect(page.get_by_text("Juego de Palas")).to_be_visible()
    print("then debe ver precio del producto “15.99”")
    expect(page.get_by_role("listitem").filter(has_text="Juego de Palas15.99 €").locator("data")).to_be_visible()
    print("then debe ver el subtotal “15.99”")
    expect(page.get_by_role("definition").filter(has_text="15.99 €").locator("data")).to_be_visible()
    print("then debe ver el IVA “3.36”")
    expect(page.get_by_text("3.36 €")).to_be_visible()
    print("then debe ver el envio “5”")
    expect(page.get_by_text("5.00 €")).to_be_visible()
    print("and debe ver el total “24”")
    expect(page.get_by_text("24.35 €")).to_be_visible()
    print("When rellena el campo de nombre válido “María Díaz”")
    page.get_by_role("textbox", name="Nombre Completo *").fill("Maria Diaz")
    print("And rellena el campo email válido “test@gmail.com”")
    page.get_by_role("textbox", name="Email *").fill("test@gmail.com")
    print("And rellena la dirección valida “Calle Aragon, 25, Madrid”")
    page.get_by_role("textbox", name="Dirección *").fill("Calle Aragon, 25, Madrid")
    print("And añade número de tarjeta invalido “1111 4242 4242 4242”")
    page.get_by_role("textbox", name="Número de Tarjeta de Crédito *").fill("1111 4242 4242 4242")
    print("And hace click en completar compra")
    page.get_by_role("button", name="Completar Compra").click()
    print("Then debe ver un mensaje de error en la tarjeta")
    expect(page.get_by_text("Tarjeta de crédito no válida.")).to_be_visible()
    
